version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 6432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Rah45ia
      - POSTGRES_USER=binto_min
      - POSTGRES_DB=binto
